### PR TITLE
Android 12.1 fix2

### PR DESCRIPTION
**Pull request by lddnsk**
2nd attempt to pull request :)
1. More partitions
2. Fix serial number in backup folder path

And I have some theme fixes in "\bootable\recovery\gui\theme" but don't understand how I can pull it because it outside of device tree

### CODE REVIEW

**Comment by lddnsk** [comment]
Also you can see in my readme.md that I have been checked at this moment and it works in my readme.md

**Comment by polygraphene** [comment]
Thank you for PR.

Those theme fixes are specific for this device?
What does that fix?

**Comment by polygraphene** [comment]
If it is small fix, patching in github workflow might be acceptable.

**Comment by lddnsk** [comment]
For example:

Screenshot_2024-11-23-20-00-14
Fixed:
Screenshot_2024-11-24-01-22-38

Screenshot_2024-11-23-19-59-26
Fixed:
Screenshot_2024-11-24-01-24-46

Screenshot_2024-11-23-20-01-17

**Comment by lddnsk** [comment]
I have modified xmls of bootable/recovery/gui/theme to fix it. Same problems with elements have in another devices recovery. This is mistake of twrp team

**Comment by polygraphene** [comment]
Ok. I see. So, please upload your bootable/recovery repo on github. I will change github workflow to include it when building.

**Comment by lddnsk** [comment]
> Ok. I see. So, please upload your bootable/recovery repo on github. I will change github workflow to include it when building.

I'll do it later. I hope to do it on this week :)

**Comment by lddnsk** [comment]
I just add zip archive to root tree
[twrp_theme_fixes.zip](https://github.com/lddnsk/android_device_lenovo_TB320FC/blob/android-12.1/twrp_theme_fixes.zip)
Take it and add files manually. Then I will remove

**Comment by polygraphene** [comment]
Thank you. I uploaded your patch on my repo and added it to github workflow.

**Pull request merged**
